client
dev tun
proto udp
remote 192.168.56.105 1194   # replace with server VM's IP
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert client1.crt
key client1.key
cipher AES-256-CBC
verb 3
