[Interface]
PrivateKey = 2LxHgPNigvhdMV0PbaNhcravrTgVyXlJQI9V2AX8SE8=
Address = 10.9.0.2/24

[Peer]
PublicKey = X1S9xm3YeOuTBtd1nsOC+f3DSA3CzVl+xYav/parzHY=
Endpoint = 192.168.56.105:51820
AllowedIPs = 10.9.0.1/32
PersistentKeepalive = 10
