[Interface]
PrivateKey = CBn245k5ECOo/0f+lzYavQt8Q2jg1Uil6DfVUGfGFlE=
Address = 10.9.0.1/24
ListenPort = 51820

[Peer]
PublicKey = POKImjFaJKorGGrXhxfe40Jw3wcxP7ixVE9h6Zwg0Ww=
AllowedIPs = 10.9.0.2/32
